In [2]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

Getting representative documents

In [ ]:
df = pd.read_csv("../../results/NLP_data_advice_fulltext.csv")
docs = df["text"].str.replace('\xa0', '', regex=False).tolist()

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    use_auth_token=False
)

embeddings = embedding_model.encode(docs, show_progress_bar=True)

topic_model = BERTopic.load(
    "../../results/NLP/BERTopic_model",
    embedding_model=embedding_model
)

doc_info = topic_model.get_document_info(docs)
topics = doc_info["Topic"].tolist()

train_idxs = np.arange(len(docs))

doc_topic = pd.DataFrame({
    "Topic": topics,
    "ID": train_idxs,
    "Document": [docs[i] for i in train_idxs]
})

topic_model._create_topic_vectors(doc_topic, embeddings[train_idxs])

repr_docs, _, _, _ = topic_model._extract_representative_docs(
    topic_model.c_tf_idf_,
    doc_topic,
    topic_model.topic_representations_,
    nr_samples=1000,
    nr_repr_docs=5
)

topic_model.representative_docs_ = repr_docs
topic_model.get_topic_info()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1241.64it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 32/32 [00:05<00:00,  6.05it/s]
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1169.91it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

   Topic  ...                                Representative_Docs
0     -1  ...  [There are 8 gnomes, each of varying colours. ...
1      0  ...  [Try each colour gnome at the beginning and if...
2      1  ...  [Be as quick as you can when choosing the gnom...
3      2  ...  [There are 8 different color gnomes, split int...
4      3  ...  [You'll see the colours in pairs, e.g. red and...
5      4  ...  [there will be 2 baskets (red and yellow) and ...
6      5  ...  [The patterns appear to be inconsistent but I ...
7      6  ...  [Have your fingers over the necessary keys at ...
8      7  ...  [There are two distinct groups of gnomes(Group...

[9 rows x 7 columns]

Save representative doc

In [24]:
topic_info = topic_model.get_topic_info()
rep_docs_expanded = pd.DataFrame(topic_info["Representative_Docs"].tolist())
out = pd.concat([topic_info[["Topic"]], rep_docs_expanded], axis=1)
out.to_csv("../../results/NLP/representative_docs.csv", index=False)

Save topic summary

In [25]:
topic_summary = topic_model.get_topic_info()
topic_summary.to_csv("../../results/NLP/topic_summary.csv")

Unclassified message

In [31]:
df = pd.read_csv("../../results/NLP_data_advice_fulltext.csv")
docs = df["text"].str.replace('\xa0', '', regex=False).tolist()

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    use_auth_token=False
)

topic_model = BERTopic.load(
    "../../results/NLP/BERTopic_model",
    embedding_model=embedding_model
)

doc_info = topic_model.get_document_info(docs)
topics = doc_info["Topic"].tolist()

new_topics = topic_model.reduce_outliers(docs, topics)
topic_model.update_topics(docs, topics=new_topics)
topic_model.get_topic_info()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1056.30it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 871.73it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
100%|██████████| 1/1 [00:00<00:00, 24.13it/s]
2026-02-25 17:40:49,158 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

   Topic  ...  Representative_Docs
0      0  ...                  NaN
1      1  ...                  NaN
2      2  ...                  NaN
3      3  ...                  NaN
4      4  ...                  NaN
5      5  ...                  NaN
6      6  ...                  NaN
7      7  ...                  NaN

[8 rows x 7 columns]

save topic reduced dataframe

In [ ]:
topic_distr, _ = topic_model.approximate_distribution(docs)
df_stat = pd.read_csv("../../data/NLP_data_stake.csv")

for topic_n in range(len(topic_distr[0,:])):
    topic_name = "topic_" + str(topic_n)
    df_stat[topic_name] = topic_distr[:, topic_n]

df_stat["assigned_topic"] = topic_model.topics_

df_stat.head()
parent_topic_weight = []
var_names = [f'topic_{n}' for n in range(len(topic_distr[0, :]))]

for i in range(len(df_stat["ID"])):
    parent_ID = df_stat["parent_ID"][i]
    parent_row = df_stat[df_stat["ID"] == parent_ID]
    if len(parent_row) < 1:
        parent_topic_weight.append([None for n in range(len(topic_distr[0, :]))])
    else:
        res = parent_row[var_names].values.tolist()
        parent_topic_weight.append(res[0])

parent_topic_df = pd.DataFrame(parent_topic_weight)
parent_topic_df.columns = [f'parent_topic_{n}' for n in range(len(topic_distr[0, :]))]

df_stat = pd.concat([df_stat, parent_topic_df], axis=1)
df_stat = df_stat.loc[:, ~df_stat.columns.str.contains('^Unnamed')]

df_stat.to_csv("../../results/NLP/data_topic_weights_reduced.csv", header=True, index=False)

  0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:00<00:00,  2.68it/s]

In [ ]:
df = pd.read_csv("../../results/NLP_data_advice_fulltext.csv")
docs = df["text"].str.replace('\xa0', '', regex=False).tolist()

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    use_auth_token=False
)

embeddings = embedding_model.encode(docs, show_progress_bar=True)

topic_model = BERTopic.load(
    "../../old/NLP/results/BERTopic_model",
    embedding_model=embedding_model
)

doc_info = topic_model.get_document_info(docs)
topics = doc_info["Topic"].tolist()

train_idxs = np.arange(len(docs))

doc_topic = pd.DataFrame({
    "Topic": topics,
    "ID": train_idxs,
    "Document": [docs[i] for i in train_idxs]
})

topic_model._create_topic_vectors(doc_topic, embeddings[train_idxs])

repr_docs, _, _, _ = topic_model._extract_representative_docs(
    topic_model.c_tf_idf_,
    doc_topic,
    topic_model.topic_representations_,
    nr_samples=1000,
    nr_repr_docs=5
)

topic_model.representative_docs_ = repr_docs
topic_model.get_topic_info()